spring:
  application:
    name: blog

  datasource:
    url: jdbc:mysql://localhost:3306/personal_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081
  servlet:
    context-path: /blog

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: claspath:mybatis/mapper/*.xml